syntax = "proto3";

package user;

// Package directory for storing generated code. userpb = package alias
option go_package = "github.com/rajsekharde/ticketing-microservices/proto/user;userpb";

// Generated code contanins UserRole prefix for all enum values
enum UserRole {
  UNSPECIFIED = 0;
  CUSTOMER = 1;
  ADMIN = 2;
}

message User {
  int64  id    = 1;
  string email = 2;
  string name  = 3;
  UserRole role = 4;
}

message GetUserRequest {
  int64 id = 1;
}

service UserService {
    rpc GetUser (GetUserRequest) returns (User);
}